#!/bin/bash

# Load resources

#xbindkeys
#syndaemon -t -k -i 1 -d &

xrdb -merge .Xresources
xsetroot -cursor_name left_ptr
setxkbmap -option compose:caps

# Set up an icon tray

#trayer --edge top --align right --SetDockType true --SetPartialStrut true \
#       --expand true --width 10 --transparent true --tint 0x191970 --height 12 &

# Set the background image
#sh ~/.fehbg &

# Fire up apps

urxvtd --quiet --opendisplay --fork

#gajim &

nvidia-settings --load-config-only &

#xscreensaver -no-splash &

#bluetooth-applet &

dropbox &

#pidgin &

pulseaudio --start

#unclutter &

#export SAL_USE_VCLPLUGIN=gen

#exec xmonad
exec i3
